server:
  port: 8301

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
      # 出现限流，调用/blocked方法
      block-page: /blocked
    loadbalancer:
      nacos:
        enabled: true